-- ============================================================================================
-- BRAIN V4 — PHASE 6b TEARDOWN: DROP the dbt-internal StarRocks databases brain_gold + brain_silver
-- ============================================================================================
--
--   ████  DESTRUCTIVE / IRREVERSIBLE DDL — READ THE GUARD BLOCK BELOW BEFORE RUNNING  ████
--
-- WHAT THIS DROPS
--   • brain_gold    — the dbt-BUILT internal Gold marts (StarRocks base tables produced by `dbt run`).
--   • brain_silver  — the dbt-BUILT internal Silver marts (StarRocks base tables produced by `dbt run`).
--
-- WHY IT IS SAFE TO DROP THESE TWO (and ONLY these two)
--   In Brain V4 the medallion is Spark→Iceberg (compute + SoR) → StarRocks async MATERIALIZED VIEWS
--   (serving). dbt-on-StarRocks is RETIRED: business truth is computed by the Spark Silver/Gold jobs
--   (db/iceberg/spark/silver/*.py + db/iceberg/spark/gold/*.py) into the EXTERNAL Iceberg catalogs, and
--   served to the app by brain_serving.mv_* (which read those Iceberg tables). Phase 4 (commit afdd3f9)
--   cut EVERY metric-engine read seam off `brain_gold.*` / `brain_silver.*` and onto `brain_serving.mv_*`.
--   Phase 6a relocated the few APP-WRITTEN native StarRocks tables that happened to live in these DBs
--   (the identity-export edges, the journey-stitch projection, the ML inference log + its watermark)
--   into the operational DB `brain_ops`. So after 6a these two DBs hold ONLY dbt-built marts that nothing
--   reads any more — they are dead weight and dropping them removes the last dbt-on-StarRocks footprint.
--
-- ────────────────────────────────────────────────────────────────────────────────────────────
--   GUARD — DO **NOT** DROP / ALTER ANY OF THE FOLLOWING. They are the V4 system of record + serving:
--     • brain_bronze_local / brain_silver_local / brain_gold_local  — EXTERNAL Iceberg catalogs (the SoR).
--     • brain_serving                                               — the mv_* serving layer over Iceberg.
--     • brain_ops                                                   — app-owned operational StarRocks state
--                                                                     (ops_ml_prediction_log, silver_identity_link,
--                                                                     silver_journey_stitch, identity_export_state).
--   ONLY the dbt-INTERNAL `brain_gold` + `brain_silver` databases are retired by this file.
-- ────────────────────────────────────────────────────────────────────────────────────────────
--
--   PRE-DROP CHECK (the HARD precondition — verify, do not assume):
--   brain_silver / brain_gold must contain NO app-WRITTEN native table (one an application job
--   INSERTs/UPSERTs/TRUNCATEs directly). Every such table must already be relocated to brain_ops (6a).
--   Run this and confirm it returns ONLY dbt-built mart names (silver_*/gold_*/stg_*/int_*/snap_* that
--   a dbt model owns) — NOT an app-written native:
--
--     SHOW TABLES FROM brain_silver;
--     SHOW TABLES FROM brain_gold;
--
--   If an app-written native table (e.g. silver_customer_identity, silver_identity_link,
--   silver_journey_stitch, identity_export_state, isolation_test) is STILL present here, STOP —
--   relocate it to brain_ops first (mirror db/starrocks/ops/ops_*.sql) and re-point its writer.
--   Dropping it while a job still writes it would break that job at runtime.
--
--   REVERSIBILITY: a DROP DATABASE is NOT reversible in place. These DBs are fully REBUILDABLE, however —
--   re-running `dbt run` against StarRocks re-materializes every mart from the Iceberg sources. So the
--   reversibility recipe is "re-run dbt" (the data is derived, never a source of truth). No data is lost
--   that is not deterministically re-derivable from Iceberg.
--
--   APPLY (loud, explicit — never folded into an automated migration):
--     docker exec -i brainv3-starrocks-1 mysql -h127.0.0.1 -P9030 -uroot < db/starrocks/teardown/drop_dbt_internal_dbs.sql
-- ============================================================================================

-- DROP the dbt-built internal Gold marts (replaced by brain_serving.mv_gold_* over Iceberg brain_gold_local).
DROP DATABASE IF EXISTS brain_gold;

-- DROP the dbt-built internal Silver marts (replaced by brain_serving.mv_silver_* over Iceberg brain_silver_local).
DROP DATABASE IF EXISTS brain_silver;

-- POST-DROP EXPECTATION (verify by hand):
--   SHOW DATABASES;  -- MUST still list: brain_serving, brain_ops, and the external brain_*_local catalogs.
--                    -- MUST NOT list:  brain_gold, brain_silver.
