apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: web-prod
  namespace: argocd
  annotations:
    argocd.argoproj.io/manifest-generate-paths: infra/helm/web
  labels:
    project: brain
    environment: prod
    service: web
spec:
  project: brain-prod
  source:
    repoURL: https://github.com/Rishabhporwal/Brain-V4.git
    targetRevision: master
    path: infra/helm/web
    helm:
      valueFiles:
        - values-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: web
  # NO automated sync for prod — manual promotion gate required
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  revisionHistoryLimit: 10
