apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cronworkflows-staging
  namespace: argocd
  annotations:
    argocd.argoproj.io/manifest-generate-paths: infra/helm/cronworkflows
  labels:
    project: brain
    environment: staging
    service: cronworkflows
spec:
  project: brain-staging
  source:
    repoURL: https://github.com/brain-platform/brain
    targetRevision: main
    path: infra/helm/cronworkflows
    helm:
      valueFiles:
        - values-staging.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: argo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  revisionHistoryLimit: 10
