/**
 * sample.collector.event.v1 — Zod contract for the canonical collector event.
 *
 * This is the SOURCE OF TRUTH for the Avro schema registered in Apicurio
 * and the TypeScript types used by the collector + stream-worker.
 *
 * INVARIANTS:
 *  - brand_id is REQUIRED — no event may be written without a tenant key (I-S01).
 *  - event_id + brand_id form the idempotency key (I-ST04).
 *  - correlation_id is REQUIRED — propagated from inbound HTTP → Kafka → Bronze (ADR-009).
 *  - occurred_at is an ISO-8601 string (UTC); stream-worker writes occurred_at as timestamptz at the Bronze
 *    boundary; no epoch-ms representation.
 *  - No raw PII fields are allowed in this schema (I-S02). Use sha256(per-brand-salt || normalized) hashes.
 *
 * Schema evolution (FULL_TRANSITIVE / additive-optional only — I-E02):
 *  - Adding an optional field with a default is ALWAYS SAFE.
 *  - Removing any field, changing a type, or renaming a field is BREAKING → rejected by Apicurio.
 */
import { z } from 'zod';

// ── Event envelope ────────────────────────────────────────────────────────────

export const CollectorEventV1Schema = z.object({
  /** Zod schema version — bump when the shape changes (additive only). */
  schema_version: z.literal('1').default('1'),

  /**
   * Unique event identifier — UUIDv4 generated by the producer.
   * Combined with brand_id to form the idempotency key (I-ST04).
   */
  event_id: z.string().uuid(),

  /**
   * Tenant key — identifies the brand this event belongs to.
   * REQUIRED: an event without a brand_id cannot be routed or stored safely (I-S01).
   */
  brand_id: z.string().uuid(),

  /**
   * Distributed trace correlation identifier — propagated from inbound HTTP header
   * (X-Correlation-Id or traceparent) through Kafka headers and into Bronze.
   * Every downstream log/trace must carry this value (ADR-009).
   */
  correlation_id: z.string().min(1).max(128),

  /**
   * Event name — dot-separated, lowercase (e.g. "page.viewed", "order.placed").
   * Used for topic routing and schema registry lookup.
   */
  event_name: z.string().min(1).max(128),

  /**
   * ISO-8601 timestamp (UTC) of when the event occurred at the source.
   * This is NOT the ingestion time; use ingest_at for that.
   */
  occurred_at: z.string().datetime({ offset: false }),

  /**
   * ISO-8601 timestamp (UTC) when the collector received the event.
   * Set by the collector; immutable once written to Bronze.
   * stream-worker writes ingested_at as timestamptz at the Bronze boundary.
   */
  ingested_at: z.string().datetime({ offset: false }).optional(),

  /**
   * Hashed identifier for the end-user (sha256(per-brand-salt || normalized_id)).
   * Never store a raw email, phone, or device ID in this field (I-S02).
   */
  hashed_user_id: z.string().max(64).optional(),

  /**
   * Hashed session identifier (sha256(per-brand-salt || session_id)).
   * Optional — not all events carry a session context.
   */
  hashed_session_id: z.string().max(64).optional(),

  /**
   * Arbitrary event properties. Values MUST NOT contain raw PII (I-S02).
   * Complex nested values should be flattened into string-serialised JSON.
   */
  properties: z.record(z.string(), z.unknown()).optional().default({}),
});

export type CollectorEventV1 = z.infer<typeof CollectorEventV1Schema>;

// ── Topic name constant ──────────────────────────────────────────────────────

/** Redpanda topic pattern: {env}.collector.event.v1 */
export const COLLECTOR_EVENT_V1_TOPIC_SUFFIX = 'collector.event.v1' as const;

// ── Avro schema name (used for Apicurio subject key) ────────────────────────
export const COLLECTOR_EVENT_V1_AVRO_SUBJECT = 'brain.collector.event.v1' as const;
