/**
 * razorpayConnectorRoutes — Fastify route for Razorpay management operations.
 *
 * POST /api/v1/connectors/razorpay/:id/rotate-webhook-secret
 *   Rotates ONLY the webhook_secret in the composite credential bundle (C2 / ADR-RZ-8),
 *   preserving key_id and key_secret. The ARN (connector_instance.secret_ref) is unchanged
 *   (NN-2). Emits a connector.webhook_secret_rotated audit-log entry (I-S02 / C5).
 *
 * RBAC: owner/admin only — webhook rotation is a high-privilege operation (destructive if
 *       the new secret is not applied to the Razorpay dashboard before the old one expires).
 *       Mount this route inside an owner/admin-guarded Fastify scope.
 *
 * I-S09: no credential values (old or new webhook_secret, key_id, key_secret) are ever
 *        logged or included in response payloads.
 */
import type { FastifyInstance, FastifyRequest, FastifyReply } from 'fastify';
import { randomUUID } from 'node:crypto';
import {
  RotateWebhookSecretCommand,
  RazorpayConnectorNotFoundForRotationError,
} from '../../application/commands/RotateWebhookSecretCommand.js';

export interface RazorpayConnectorRouteDeps {
  rotateWebhookSecret: RotateWebhookSecretCommand;
  /** Extracts the brand_id from the authenticated JWT/session. Called per-request. */
  getBrandId: (req: FastifyRequest) => string;
  /** Optional audit hook called after a successful rotation. */
  onRotated?: (brandId: string, connectorInstanceId: string) => Promise<void>;
}

/**
 * Registers the Razorpay management routes. Mount this inside a Fastify scope that already
 * applies the session preHandler + an owner/admin RBAC guard (mirrors the pattern used for
 * the generic connector write scope in main.ts).
 */
export function registerRazorpayConnectorRoutes(
  fastify: FastifyInstance,
  deps: RazorpayConnectorRouteDeps,
): void {
  /**
   * POST /api/v1/connectors/razorpay/:id/rotate-webhook-secret
   *
   * Body: { new_webhook_secret: string, razorpay_account_id: string }
   *   - new_webhook_secret: the new webhook_secret to store (generated by the caller or Razorpay
   *     dashboard). Must match what is configured in the Razorpay merchant dashboard.
   *   - razorpay_account_id: the Razorpay merchant account ID used as the secret name sub-key
   *     (needed to reconstruct the secret name for the in-place update — same as connect).
   *
   * Response 200: { request_id, data: { rotated: true } }
   * Response 404: connector not found for this brand.
   * Response 400: missing/invalid body.
   */
  fastify.post(
    '/api/v1/connectors/razorpay/:id/rotate-webhook-secret',
    async (
      req: FastifyRequest<{
        Params: { id: string };
        Body: { new_webhook_secret?: string; razorpay_account_id?: string };
      }>,
      reply: FastifyReply,
    ) => {
      const requestId = (req.id as string) ?? randomUUID();
      const brandId = deps.getBrandId(req);
      const connectorInstanceId = req.params.id;
      const body = req.body ?? {};

      // Input validation.
      if (!body.new_webhook_secret || typeof body.new_webhook_secret !== 'string') {
        return reply.code(400).send({
          request_id: requestId,
          error: { code: 'MISSING_WEBHOOK_SECRET', message: 'new_webhook_secret is required.' },
        });
      }
      if (!body.razorpay_account_id || typeof body.razorpay_account_id !== 'string') {
        return reply.code(400).send({
          request_id: requestId,
          error: { code: 'MISSING_RAZORPAY_ACCOUNT_ID', message: 'razorpay_account_id is required.' },
        });
      }

      try {
        await deps.rotateWebhookSecret.execute({
          connectorInstanceId,
          brandId,
          newWebhookSecret: body.new_webhook_secret,
          razorpayAccountId: body.razorpay_account_id,
        });

        // Audit-log the rotation (I-S02 / C5 — no secret values in payload).
        if (deps.onRotated) {
          await deps.onRotated(brandId, connectorInstanceId);
        }

        // I-S09: do NOT echo back any credential values.
        return reply.code(200).send({
          request_id: requestId,
          data: { rotated: true },
        });
      } catch (err) {
        if (err instanceof RazorpayConnectorNotFoundForRotationError) {
          return reply.code(404).send({
            request_id: requestId,
            error: { code: 'CONNECTOR_NOT_FOUND', message: err.message },
          });
        }
        throw err;
      }
    },
  );
}
