"""
serving_preagg_refresh.py — AUD-SL-10: the scheduled MATERIALIZER for the semantic-layer pre-aggs
(DuckDB port of the retired apps/core/src/jobs/semantic-preagg-refresh.ts — Trino removal, ADR-0014).

WHAT IT DOES: applies the semantic ENTITY views (db/iceberg/duckdb/views/semantic_*.sql — the D.1
views the compiled pre-agg SQL reads FROM) into a LOCAL brain_serving schema, then executes every
compiler-emitted rebuild statement in serving_preaggs/*.duckdb.sql. Each file is CREATE TABLE IF
NOT EXISTS + ONE DELETE+INSERT TRANSACTION into iceberg.brain_serving.preagg_* — a single Iceberg
replace commit, so catalog readers (duckdb-serving) see the previous rows until the transaction
commits, never an empty table mid-refresh. DuckDB-Iceberg has no CREATE OR REPLACE TABLE over a
REST catalog (Phase-0 gate f), which is why the transactional DELETE+INSERT form is the atomic
rebuild.

WHY A TRANSFORM-TIER JOB (not duckdb-serving, not the core image): the pre-agg sources are the
semantic entity views, which read the Iceberg Silver/Gold marts — a cross-brand batch aggregation,
i.e. transform work. duckdb-serving attaches READ-ONLY (it can never write a pre-agg); this job
attaches read-write through the SAME _catalog.py seam the Silver/Gold marts use. The generated SQL
is committed HERE (db/iceberg/duckdb/serving_preaggs/, next to this job) because the brain-duckdb
image builds with context db/iceberg — the existing `COPY duckdb/` carries both to /opt/brain/duckdb.
The SQL is GENERATED by the @brain/semantic-metrics compiler and snapshot-pinned (D2.snapshot) —
never hand-edit it; change the YAML + `pnpm --filter @brain/semantic-metrics compile`.

TENANCY: this is a CROSS-BRAND batch build — brand_id is a GROUPING KEY in every pre-agg, not a
predicate (the same posture as the Gold marts). Serving reads NEVER touch these tables directly:
they go through the compiled `brain_serving.mv_metric_*` views, which embed the ${BRAND_PREDICATE}
seam (compile-time row-level tenancy) — enforced by the D2.tenancy compiler tests.

FAILURE POSTURE (parity with the retired TS job): one table failing must not starve the rest —
errors are collected per file and the job exits non-zero if ANY failed (the CronWorkflow surfaces
a partial failure). A missing/empty serving_preaggs/ dir is a PACKAGING bug (the image must carry
the generated SQL) → hard fail. A missing views/ dir or an unapplyable view is tolerated
(continue-on-error, run-trino-views semantics): the dependent pre-aggs then fail loudly per-table.
Idempotent: re-running just replaces the tables again.

Invoked by the cronworkflows chart (`python /opt/brain/duckdb/serving_preagg_refresh.py`,
brain-duckdb image) hourly at :40 — the entity views read Gold marts the */5 v4-gold cron keeps fresh.
"""
from __future__ import annotations

import glob
import json
import os
import sys
import time

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

# The generated pre-agg SQL and the ported serving views HARDCODE the `iceberg` catalog handle
# (the same handle duckdb-serving attaches as). Pin it BEFORE importing _catalog (which reads the
# env at import time) so a transform-tier default (ICEBERG_CATALOG=rest, e.g. inherited from the
# v4-silver/v4-gold env) can never leave the iceberg.brain_serving.preagg_* targets unresolvable.
os.environ["ICEBERG_CATALOG"] = "iceberg"

from _catalog import CATALOG, SERVING_NAMESPACE, connect  # noqa: E402

HERE = os.path.dirname(os.path.abspath(__file__))
# The semantic entity views (the ported serving views, db/iceberg/duckdb/views/semantic_*.sql).
# May not exist on an older image/checkout — tolerated (see FAILURE POSTURE above); override for
# a test harness.
VIEWS_DIR = os.environ.get("SERVING_VIEWS_DIR", os.path.join(HERE, "views"))
# The compiler-emitted rebuild statements (snapshot-pinned generated artifacts — see the header).
PREAGG_SQL_DIR = os.environ.get("SEMANTIC_PREAGG_SQL_DIR", os.path.join(HERE, "serving_preaggs"))


def apply_semantic_views(con) -> tuple[int, list[str]]:
    """
    Apply the semantic entity views into a LOCAL brain_serving schema (which SHADOWS the attached
    catalog's brain_serving namespace for two-part names — Phase-0 gate d), continue-on-error like
    run-trino-views.sh: a view over a mart that has not been built yet must not abort the rest.
    Returns (applied, skipped-names).
    """
    con.execute("CREATE SCHEMA IF NOT EXISTS brain_serving;")
    applied, skipped = 0, []
    if not os.path.isdir(VIEWS_DIR):
        print(f'{{"job":"serving-preagg-refresh","warn":"views dir missing: {VIEWS_DIR} — '
              f'semantic views not applied; pre-aggs will fail per-table if absent"}}', flush=True)
        return applied, skipped
    for path in sorted(glob.glob(os.path.join(VIEWS_DIR, "semantic_*.sql"))):
        name = os.path.basename(path)
        try:
            with open(path, encoding="utf-8") as f:
                con.execute(f.read())
            applied += 1
        except Exception as e:  # noqa: BLE001 — dependency not ready → skip, surface at the end
            skipped.append(name)
            print(f'{{"job":"serving-preagg-refresh","view_skipped":{json.dumps(name)},'
                  f'"error":{json.dumps(str(e).splitlines()[0][:300])}}}', flush=True)
    return applied, skipped


def refresh_preaggs(con) -> tuple[int, int, int]:
    """Execute every serving_preaggs/*.duckdb.sql (one atomic rebuild per file, errors collected
    per table — parity with the retired TS job). Returns (tables, refreshed, errors)."""
    files = sorted(glob.glob(os.path.join(PREAGG_SQL_DIR, "*.duckdb.sql")))
    if not files:
        # The generated SQL is committed next to this job and COPY'd into the image — absence is a
        # packaging/build bug, not an empty-registry state. Fail loudly (never a silent no-op).
        raise RuntimeError(f"no *.duckdb.sql under {PREAGG_SQL_DIR} — the image/checkout is missing "
                           f"the compiler-emitted pre-agg SQL (pnpm --filter @brain/semantic-metrics compile)")
    refreshed, errors = 0, 0
    for path in files:
        table = os.path.basename(path).replace(".duckdb.sql", "")
        t0 = time.time()
        try:
            with open(path, encoding="utf-8") as f:
                sql = f.read()
            con.execute(sql)
            refreshed += 1
            print(f'{{"job":"serving-preagg-refresh","preagg":"{table}",'
                  f'"seconds":{time.time() - t0:.2f},"engine":"duckdb"}}', flush=True)
        except Exception as e:  # noqa: BLE001 — one table must not starve the rest
            errors += 1
            # A failed transaction can leave the connection mid-transaction — roll back so the
            # NEXT file's BEGIN doesn't error with "transaction is already active".
            try:
                con.execute("ROLLBACK;")
            except Exception:  # noqa: BLE001 — nothing open → fine
                pass
            print(f'{{"job":"serving-preagg-refresh","preagg":"{table}","FAILED":true,'
                  f'"seconds":{time.time() - t0:.2f},'
                  f'"error":{json.dumps(str(e).splitlines()[0][:300])}}}', flush=True)
    return len(files), refreshed, errors


def main() -> int:
    t0 = time.time()
    con = connect()
    try:
        # Sanity: the serving namespace must exist in the catalog (the targets live there).
        con.execute(f"CREATE SCHEMA IF NOT EXISTS {CATALOG}.{SERVING_NAMESPACE};")
        views_applied, views_skipped = apply_semantic_views(con)
        tables, refreshed, errors = refresh_preaggs(con)
        print(f'{{"job":"serving-preagg-refresh","tables":{tables},"refreshed":{refreshed},'
              f'"errors":{errors},"views_applied":{views_applied},'
              f'"views_skipped":{json.dumps(views_skipped)},'
              f'"seconds":{time.time() - t0:.2f},"engine":"duckdb"}}', flush=True)
        # Exit non-zero on ANY table failure so the CronWorkflow surfaces a partial failure.
        return 1 if errors > 0 else 0
    finally:
        con.close()


if __name__ == "__main__":
    sys.exit(main())
