// SPEC:D.2
/**
 * @brain/semantic-metrics — the COMPILER.
 *
 * Deterministic, pure (no I/O): a validated MetricDefinition → its compiled artifacts. Governance
 * (§D.2): metric SQL is NEVER hand-written — it is a function of the YAML, regenerated by this
 * compiler, and pinned by the D2.snapshot test so silent drift is impossible.
 *
 * Per metric×grain the compiler emits (all snapshot-pinned):
 *   • viewSql        — the CANONICAL compiled view (a DuckDB-serving query TEMPLATE). For an
 *                      `interactive` time-grain it reads the pre-agg; for a `slow`/`all` grain it
 *                      reads the base semantic entity. Every view embeds the literal ${BRAND_PREDICATE}
 *                      sentinel EXACTLY ONCE (compile-time row-level tenancy, AMD-07 D3).
 *   • preaggDdl / preaggRefreshSql — for `interactive` time-grains: the scheduled Iceberg
 *                      pre-aggregation (additive MEASURES only; the non-additive metric value is
 *                      derived at read). §1.11.1.
 *   • baseFallbackSql — for `interactive` time-grains: the base-entity view for dims NOT covered by
 *                      the pre-agg (the §1.11.1 long-tail fallback).
 *
 * §1.4 determinism proof: a `deterministic_only` metric is compiled so probabilistic rows are
 * PROVABLY excluded — either the compiler injects `identity_basis = 'deterministic'` (entities that
 * carry the physical column) or the entity is `deterministicByConstruction` (recorded in entities.ts).
 * Neither ⇒ the compiler FAILS CLOSED.
 */

import { BRAND_PREDICATE, resolveEntity, type EntityBinding } from './entities.js';
import type { MetricDefinition, Measure, TimeGrain, SemanticEntity } from './schema.js';

// ── SQL identifier extraction (for cross-entity UNION column projection) ───────────────────────
const AGG_KEYWORDS = new Set([
  'sum', 'count', 'avg', 'min', 'max', 'distinct', 'case', 'when', 'then', 'else', 'end',
  'coalesce', 'nullif', 'cast', 'as', 'double', 'bigint', 'decimal', 'and', 'or', 'not',
  'true', 'false', 'null', 'filter', 'where', 'over', 'approx_distinct',
]);

/** Extract the base COLUMN identifiers referenced by a measure aggregate (drops functions/keywords). */
function measureColumns(agg: string): string[] {
  const out: string[] = [];
  for (const tok of agg.match(/[a-z_][a-z0-9_]*/g) ?? []) {
    if (AGG_KEYWORDS.has(tok)) continue;
    if (!out.includes(tok)) out.push(tok);
  }
  return out;
}

/** date_trunc bucket expression for a time-bucketed grain; null for grain `all`. */
function bucketExpr(grain: TimeGrain, timeColumn: string): string | null {
  if (grain === 'all') return null;
  return `date_trunc('${grain}', ${timeColumn})`;
}

/** The §1.4 basis predicate for one entity under a deterministic_only metric (may be empty). */
function basisPredicate(binding: EntityBinding, deterministicOnly: boolean, entity: SemanticEntity): string | null {
  if (!deterministicOnly) return null;
  if (binding.identityBasisColumn) return `${binding.identityBasisColumn} = 'deterministic'`;
  if (binding.deterministicByConstruction) return null; // provable by construction (entities.ts)
  throw new Error(
    `[semantic-metrics] metric on entity '${entity}' is identity_basis=deterministic_only but the ` +
      `entity has no identity_basis column and is not deterministicByConstruction — cannot PROVE ` +
      `probabilistic exclusion (§1.4). Fix entities.ts or the metric's identity_basis.`,
  );
}

export interface CompiledPreagg {
  readonly tableName: string;
  readonly createDdl: string;
  readonly refreshSql: string;
  /**
   * AUD-SL-10 — the ATOMIC DuckDB materialization: CREATE TABLE IF NOT EXISTS + ONE DELETE+INSERT
   * TRANSACTION (a single Iceberg replace commit — readers see the old rows until the transaction
   * commits, never an empty table mid-refresh). DuckDB-Iceberg does NOT support CREATE OR REPLACE
   * TABLE over a REST catalog (Phase-0 gate f), so the DELETE+INSERT transactional form is the
   * atomic rebuild. This is what the scheduled semantic-preagg-refresh job
   * (db/iceberg/duckdb/serving_preagg_refresh.py) executes: the source entity views
   * (brain_serving.semantic_*) are LOCAL DuckDB views the job applies from
   * db/iceberg/duckdb/views/ before materializing. createDdl/refreshSql (the dormant Spark
   * dialect) remain committed for audit continuity; ONE materializer owns a table at a time.
   */
  readonly duckdbRefreshSql: string;
}

export interface CompiledGrain {
  readonly grain: TimeGrain;
  readonly viewName: string;
  /** The canonical compiled view SQL (template with ${BRAND_PREDICATE}). */
  readonly viewSql: string;
  /** Present only for interactive time-grains (§1.11.1). */
  readonly preagg?: CompiledPreagg;
  /** Present only for interactive time-grains: base-entity fallback for uncovered dims. */
  readonly baseFallbackSql?: string;
}

export interface CompiledMetric {
  readonly name: string;
  readonly version: string;
  readonly entity: SemanticEntity;
  readonly interactive: boolean;
  readonly grains: readonly CompiledGrain[];
}

// ── grouping-key + select assembly ─────────────────────────────────────────────────────────────

interface GroupPlan {
  /** Ordered non-measure output columns (brand_id, period?, currency_code?, ...dims). */
  readonly keySelect: string[];
  /** GROUP BY ordinals string, e.g. "1, 2, 3". */
  readonly groupBy: string;
  /** Whether currency_code is a grouping key for this metric. */
  readonly withCurrency: boolean;
}

function planGroups(m: MetricDefinition, grain: TimeGrain, binding: EntityBinding): GroupPlan {
  const withCurrency = m.currency_handling !== 'none' && binding.hasCurrency;
  const keys: string[] = ['brand_id'];
  const bucket = bucketExpr(grain, m.time_column);
  if (bucket) keys.push(`${bucket} AS period`);
  if (withCurrency) keys.push('currency_code');
  for (const d of m.dimensions_allowed) keys.push(d);
  const groupBy = keys.map((_, i) => String(i + 1)).join(', ');
  return { keySelect: keys, groupBy, withCurrency };
}

/** Output key columns as bare names (for the outer projection over `base`). */
function keyNames(m: MetricDefinition, grain: TimeGrain, withCurrency: boolean): string[] {
  const names = ['brand_id'];
  if (grain !== 'all') names.push('period');
  if (withCurrency) names.push('currency_code');
  names.push(...m.dimensions_allowed);
  return names;
}

// ── single-entity compilation (base view) ──────────────────────────────────────────────────────

function baseViewSql(m: MetricDefinition, grain: TimeGrain, viewName: string): string {
  const binding = resolveEntity(m.entity);
  const plan = planGroups(m, grain, binding);
  const names = keyNames(m, grain, plan.withCurrency);

  const wheres: string[] = [];
  if (grain !== 'all') wheres.push(`${m.time_column} IS NOT NULL`);
  const basis = basisPredicate(binding, m.identity_basis === 'deterministic_only', m.entity);
  if (basis) wheres.push(basis);
  wheres.push(BRAND_PREDICATE); // EXACTLY ONE — compile-time tenancy
  const whereSql = wheres.map((w, i) => (i === 0 ? `  WHERE ${w}` : `    AND ${w}`)).join('\n');

  const measureSelect = m.measures.map((x) => `    ${x.agg} AS ${x.name}`).join(',\n');
  const keySelect = plan.keySelect.map((k) => `    ${k}`).join(',\n');
  const measureNames = m.measures.map((x) => x.name);

  return (
    `-- SPEC:D.2 — compiled metric view: ${m.name} (${m.version}) @ grain=${grain} · entity=${m.entity}\n` +
    `-- GENERATED by @brain/semantic-metrics compiler — DO NOT EDIT. Change the YAML + recompile.\n` +
    `-- Tenancy: the BRAND_PREDICATE sentinel (below) is replaced with \`brand_id = ?\` by the serving seam.\n` +
    `CREATE OR REPLACE VIEW ${viewName} AS\n` +
    `WITH base AS (\n` +
    `  SELECT\n${keySelect},\n${measureSelect}\n` +
    `  FROM ${binding.table}\n` +
    `${whereSql}\n` +
    `  GROUP BY ${plan.groupBy}\n` +
    `)\n` +
    `SELECT\n` +
    `${[...names, ...measureNames].map((n) => `  ${n}`).join(',\n')},\n` +
    `  (${m.expression}) AS ${m.name}\n` +
    `FROM base;\n`
  );
}

// ── cross-entity compilation (UNION-ALL then single brand filter) ────────────────────────────────

function crossViewSql(m: MetricDefinition, viewName: string): string {
  // Cross-entity metrics are grain `all` only (schema-enforced): join on (brand_id[, currency_code]).
  const grain: TimeGrain = 'all';
  const primary = resolveEntity(m.entity);
  const cross = resolveEntity(m.cross!.entity);
  const withCurrency = m.currency_handling !== 'none' && primary.hasCurrency && cross.hasCurrency;

  // Columns each leg must project (for the UNION-ALL superset).
  const baseCols = dedupe(m.measures.flatMap((x) => measureColumns(x.agg)));
  const crossCols = dedupe(m.cross!.measures.flatMap((x) => measureColumns(x.agg)));
  const allCols = dedupe([...baseCols, ...crossCols]);

  const projLeg = (leg: 'base' | 'cross', own: string[]): string => {
    // A column not owned by this leg is a bare NULL placeholder — the engine coerces the
    // unknown-typed NULL to the concrete type of the sibling leg's column across the UNION ALL
    // (never CAST here: the compiler doesn't know the column's physical type, and a wrong CAST
    // would break the union).
    const cols = allCols.map((c) => (own.includes(c) ? `${c} AS ${c}` : `NULL AS ${c}`));
    const cur = withCurrency ? ['currency_code'] : [];
    return [`    brand_id`, ...cur.map((c) => `    ${c}`), `    '${leg}' AS __src`, ...cols.map((c) => `    ${c}`)].join(',\n');
  };

  // §1.4 basis predicate is applied per-leg (physical-basis entities only); brand predicate is outer.
  const primBasis = basisPredicate(primary, m.identity_basis === 'deterministic_only', m.entity);
  const crossBasis = basisPredicate(cross, m.identity_basis === 'deterministic_only', m.cross!.entity);
  const primWhere = primBasis ? `\n  WHERE ${primBasis}` : '';
  const crossWhere = crossBasis ? `\n  WHERE ${crossBasis}` : '';

  const measureAgg = (x: Measure, leg: 'base' | 'cross'): string =>
    `    ${x.agg} FILTER (WHERE __src = '${leg}') AS ${x.name}`;
  const aggSelect = [
    ...m.measures.map((x) => measureAgg(x, 'base')),
    ...m.cross!.measures.map((x) => measureAgg(x, 'cross')),
  ].join(',\n');

  const keyCols = withCurrency ? ['brand_id', 'currency_code'] : ['brand_id'];
  const groupBy = keyCols.map((_, i) => String(i + 1)).join(', ');
  const measureNames = [...m.measures, ...m.cross!.measures].map((x) => x.name);

  return (
    `-- SPEC:D.2 (AMD-25) — compiled CROSS-ENTITY metric view: ${m.name} (${m.version}) @ grain=all\n` +
    `-- primary=${m.entity} × cross=${m.cross!.entity} — blended whole-period, joined on (${keyCols.join(', ')}).\n` +
    `-- GENERATED by @brain/semantic-metrics compiler — DO NOT EDIT. Change the YAML + recompile.\n` +
    `CREATE OR REPLACE VIEW ${viewName} AS\n` +
    `WITH unioned AS (\n` +
    `  SELECT\n${projLeg('base', baseCols)}\n  FROM ${primary.table}${primWhere}\n` +
    `  UNION ALL\n` +
    `  SELECT\n${projLeg('cross', crossCols)}\n  FROM ${cross.table}${crossWhere}\n` +
    `),\n` +
    `agg AS (\n` +
    `  SELECT\n${keyCols.map((k) => `    ${k}`).join(',\n')},\n${aggSelect}\n` +
    `  FROM unioned\n` +
    `  WHERE ${BRAND_PREDICATE}\n` +
    `  GROUP BY ${groupBy}\n` +
    `)\n` +
    `SELECT\n${[...keyCols, ...measureNames].map((n) => `  ${n}`).join(',\n')},\n` +
    `  (${m.expression}) AS ${m.name}\n` +
    `FROM agg;\n`
  );
}

// ── pre-aggregation (interactive time-grains, §1.11.1) ───────────────────────────────────────────

function compilePreagg(m: MetricDefinition, grain: TimeGrain): CompiledPreagg {
  const binding = resolveEntity(m.entity);
  const plan = planGroups(m, grain, binding);
  const tableName = `iceberg.brain_serving.preagg_${m.name}_${grain}`;

  // Column DDL: brand_id + period + currency? + dims + additive measures (all bigint minor / counts).
  const cols: string[] = ['  brand_id varchar'];
  cols.push('  period timestamp(6)');
  if (plan.withCurrency) cols.push('  currency_code varchar');
  for (const d of m.dimensions_allowed) cols.push(`  ${d} varchar`);
  for (const x of m.measures) cols.push(`  ${x.name} bigint`);

  const createDdl =
    `-- SPEC:D.2 / §1.11.1 — Spark-maintained pre-agg for interactive metric ${m.name} @ grain=${grain}.\n` +
    `-- Additive MEASURES only; the non-additive metric value is derived at read in the view.\n` +
    `CREATE TABLE IF NOT EXISTS ${tableName} (\n${cols.join(',\n')}\n)\n` +
    `USING iceberg\n` +
    `PARTITIONED BY (bucket(16, brand_id))\n` +
    `TBLPROPERTIES ('format-version'='2', 'write.delete.mode'='merge-on-read');\n`;

  // Full rebuild across ALL brands (batch): brand_id is a grouping key, NO brand predicate here.
  const wheres: string[] = [`${m.time_column} IS NOT NULL`];
  const basis = basisPredicate(binding, m.identity_basis === 'deterministic_only', m.entity);
  if (basis) wheres.push(basis);
  const measureSelect = m.measures.map((x) => `    ${x.agg} AS ${x.name}`).join(',\n');
  const keySelect = plan.keySelect.map((k) => `    ${k}`).join(',\n');

  const refreshSql =
    `-- SPEC:D.2 / §1.11.1 — refresh (idempotent full rebuild) for ${tableName}. Run by the Spark refresh loop.\n` +
    `INSERT OVERWRITE ${tableName}\n` +
    `SELECT\n${keySelect},\n${measureSelect}\n` +
    `FROM ${binding.table}\n` +
    `  WHERE ${wheres.join('\n    AND ')}\n` +
    `GROUP BY ${plan.groupBy};\n`;

  // AUD-SL-10 — the DuckDB ATOMIC rebuild. DuckDB-Iceberg has NO `CREATE OR REPLACE TABLE` over a
  // REST catalog (Phase-0 gate f: "use separate Drop and Create Statements"), so the atomic form is
  // CREATE TABLE IF NOT EXISTS (first run) + ONE DELETE+INSERT TRANSACTION — one Iceberg replace
  // commit; catalog readers see the previous snapshot until COMMIT, never an empty table. Same
  // plan/measures/predicates as refreshSql — only the DDL dialect differs (DuckDB `PARTITIONED BY`
  // + string/timestamptz/bigint column types, the transform tier's ensure_table conventions).
  // Cross-brand batch (brand_id is a grouping key, NO brand predicate) — consumers read through the
  // compiled ${'{BRAND_PREDICATE}'}-guarded views, never this table directly.
  const duckCols: string[] = ['  brand_id string'];
  duckCols.push('  period timestamptz');
  if (plan.withCurrency) duckCols.push('  currency_code string');
  for (const d of m.dimensions_allowed) duckCols.push(`  ${d} string`);
  for (const x of m.measures) duckCols.push(`  ${x.name} bigint`);
  const duckdbRefreshSql =
    `-- SPEC:D.2 / §1.11.1 / AUD-SL-10 — ATOMIC DuckDB materialization for ${tableName}.\n` +
    `-- Run by the semantic-preagg-refresh cron (db/iceberg/duckdb/serving_preagg_refresh.py).\n` +
    `-- GENERATED — DO NOT EDIT (change the YAML + recompile: pnpm --filter @brain/semantic-metrics compile).\n` +
    `CREATE TABLE IF NOT EXISTS ${tableName} (\n${duckCols.join(',\n')}\n)\n` +
    `PARTITIONED BY (bucket(16, brand_id));\n` +
    `\n` +
    `BEGIN TRANSACTION;\n` +
    `\n` +
    `DELETE FROM ${tableName};\n` +
    `\n` +
    `INSERT INTO ${tableName}\n` +
    `SELECT\n${keySelect},\n${measureSelect}\n` +
    `FROM ${binding.table}\n` +
    `  WHERE ${wheres.join('\n    AND ')}\n` +
    `GROUP BY ${plan.groupBy};\n` +
    `\n` +
    `COMMIT;\n`;

  return { tableName, createDdl, refreshSql, duckdbRefreshSql };
}

function preaggViewSql(m: MetricDefinition, grain: TimeGrain, viewName: string, preagg: CompiledPreagg): string {
  const binding = resolveEntity(m.entity);
  const withCurrency = m.currency_handling !== 'none' && binding.hasCurrency;
  const names = keyNames(m, grain, withCurrency);
  const measureNames = m.measures.map((x) => x.name);
  return (
    `-- SPEC:D.2 / §1.11.1 — compiled INTERACTIVE metric view: ${m.name} (${m.version}) @ grain=${grain}.\n` +
    `-- Reads the pre-agg ${preagg.tableName} (covered dims). Long-tail/uncovered dims → the\n` +
    `-- base-entity fallback view ${viewName}_slow. Tenancy: BRAND_PREDICATE sentinel → \`brand_id = ?\`.\n` +
    `-- GENERATED by @brain/semantic-metrics compiler — DO NOT EDIT. Change the YAML + recompile.\n` +
    `CREATE OR REPLACE VIEW ${viewName} AS\n` +
    `SELECT\n${[...names, ...measureNames].map((n) => `  ${n}`).join(',\n')},\n` +
    `  (${m.expression}) AS ${m.name}\n` +
    `FROM ${preagg.tableName}\n` +
    `WHERE ${BRAND_PREDICATE};\n`
  );
}

function dedupe<T>(xs: T[]): T[] {
  return [...new Set(xs)];
}

// ── top-level compile ────────────────────────────────────────────────────────────────────────────

/** View name for a metric×grain: mv_metric_<name>_<grain>. Two-part: the compiled views live in
 *  duckdb-serving's LOCAL brain_serving schema (which shadows the catalog namespace), NOT in the
 *  attached `iceberg` catalog — only physical tables (the preagg_* targets) are three-part. */
export function metricViewName(name: string, grain: TimeGrain): string {
  return `brain_serving.mv_metric_${name}_${grain}`;
}

/** Compile ONE validated metric into its per-grain artifacts. Pure + deterministic. */
export function compileMetric(m: MetricDefinition): CompiledMetric {
  const grains: CompiledGrain[] = m.grain.map((grain) => {
    const viewName = metricViewName(m.name, grain);

    if (m.cross) {
      // Cross-entity → single blended `all`-grain view (schema guarantees grain === 'all').
      return { grain, viewName, viewSql: crossViewSql(m, viewName) };
    }

    const interactiveGrain = m.interactive && grain !== 'all';
    if (interactiveGrain) {
      const preagg = compilePreagg(m, grain);
      const slowName = `${viewName}_slow`;
      return {
        grain,
        viewName,
        viewSql: preaggViewSql(m, grain, viewName, preagg),
        preagg,
        baseFallbackSql: baseViewSql(m, grain, slowName),
      };
    }

    return { grain, viewName, viewSql: baseViewSql(m, grain, viewName) };
  });

  return {
    name: m.name,
    version: m.version,
    entity: m.entity,
    interactive: m.interactive,
    grains,
  };
}
