'use client';

/**
 * RetentionContent — Tab #7 "Do customers come back?".
 *
 * Answers the retention question from the existing data layer:
 *   - Repeat-purchase rate — share of customers with 2+ orders (engine-derived, exec metrics).
 *   - Acquisition-cohort curve — for each cohort-month: size, lifetime orders + value, and
 *     orders-per-customer (the repeat signal), from gold_cohorts via the metric registry.
 *
 * GAP this slice CLOSED (thin): the BFF endpoint /v1/analytics/cohort-retention + the gold_cohorts
 * mart already existed server-side, but the WEB client had no getCohortRetention fn and no hook.
 * Added analyticsApi.getCohortRetention + useCohortRetention (no new backend) — see lib/api/client.ts
 * + lib/hooks/use-analytics.ts.
 *
 * GENUINE GAP still open (flagged, NOT faked → EmptyState + openItem): "time-to-2nd-purchase"
 * (median days between a customer's 1st and 2nd order) is exposed by NO existing endpoint and would
 * need a new backend aggregate over the order spine. We do not fabricate a histogram.
 *
 * Honesty: money is bigint minor units + currency_code, formatted ONLY via formatMoneyDisplay; ratios
 * (orders_per_customer, repeat_rate_pct) come straight from the engine — never re-divided with floats
 * in the client; counts summed across cohorts use BigInt. FreshnessBadge now reads a REAL relative time
 * from the served_at (generated_at) the cohort/exec endpoints return — never a fabricated "just now".
 * EmptyState on no_data — never a fake zero.
 */

import { useState } from 'react';
import Link from 'next/link';
import { Repeat, Users, Layers, Hourglass, ArrowRight, History } from 'lucide-react';
import type { CurrencyCode } from '@brain/money';
import { CohortHeatmap, type CohortHeatmapRow } from '@/components/analytics/cohort-heatmap';
import { TabShell } from '@/components/ui/tab-shell';
import { SectionCard } from '@/components/ui/section-card';
import { EmptyState } from '@/components/ui/empty-state';
import { FreshnessBadge } from '@/components/ui/freshness-badge';
import { MetricCard } from '@/components/ui/metric-card';
import { Button } from '@/components/ui/button';
import { Skeleton } from '@/components/ui/skeleton';
import { ErrorCard } from '@/components/ui/error-card';
import {
  Table,
  TableHeader,
  TableBody,
  TableHead,
  TableRow,
  TableCell,
} from '@/components/ui/table';
import { formatMoneyDisplay } from '@/lib/format/money-display';
import { useCohortRetention, useExecutiveMetrics, useRepeatLatency } from '@/lib/hooks/use-analytics';
import type {
  AnalyticsCohortRetentionResponse,
  AnalyticsCohortRetentionRow,
  AnalyticsRepeatLatencyResponse,
} from '@/lib/api/types';

type CohortHasData = Extract<AnalyticsCohortRetentionResponse, { state: 'has_data' }>;
type RepeatLatencyHasData = Extract<AnalyticsRepeatLatencyResponse, { state: 'has_data' }>;

const EXPLAINER = {
  title: 'Retention — Do customers come back?',
  description:
    'The overall repeat-purchase rate plus an acquisition-cohort curve: for each month’s new customers, how many lifetime orders and how much value they generate, and how many orders each makes on average.',
  metrics: [
    {
      name: 'Repeat-purchase rate',
      definition: 'Share of customers who have placed 2+ orders.',
      howComputed: 'Executive metrics repeat_rate_pct over the Gold marts (engine-derived; null when there are no customers).',
    },
    {
      name: 'Cohort size',
      definition: 'New customers first acquired in that calendar month.',
      howComputed: 'gold_cohorts, grouped by acquisition month, via /v1/analytics/cohort-retention.',
    },
    {
      name: 'Orders per customer',
      definition: 'Average lifetime orders made by that cohort — the repeat signal (>1 means customers came back).',
      howComputed: 'Exact decimal from the engine (cohort lifetime orders ÷ cohort size); null when the cohort is empty. Never re-divided in the client.',
    },
    {
      name: 'Lifetime value',
      definition: 'Total realized value generated by that cohort to date.',
      howComputed: 'gold_cohorts realized value, bigint minor units + currency_code, formatted via formatMoneyDisplay.',
    },
    {
      name: 'Repeat-order share (heatmap)',
      definition: 'Of all the orders a cohort has placed, the share that were repeat (2nd-or-later) purchases — the come-back signal as a percentage.',
      howComputed: 'Exact integer math on the engine counts: (cohort lifetime orders − cohort size) ÷ cohort lifetime orders, computed with BigInt (no floats, never blended). Null → em-dash when the cohort has no orders yet.',
    },
    {
      name: 'Value share (heatmap)',
      definition: 'Each cohort’s share of the total lifetime realized value across all cohorts — which acquisition months drive the value.',
      howComputed: 'Exact BigInt math on bigint minor-unit value (cohort value ÷ Σ cohort value); never a float, never /100. Null → em-dash when total value is zero.',
    },
  ],
  sections: [
    {
      heading: 'How to read the cohort heatmap',
      body: 'Each row is one acquisition month, shaded red → amber → green by the selected metric (use “Shade by” to switch between repeat-order share and value share). The percentage is always printed in the cell, so colour is only a redundant cue. Compare rows top-to-bottom: older cohorts have had longer to come back, so a healthy business greens-up for mature cohorts. The “Exact figures” table below carries the lifetime orders, orders-per-customer and lifetime value (money) behind the shading.',
    },
    {
      heading: 'Time-to-2nd-purchase',
      body: 'The median days between a customer’s 1st and 2nd order, plus a six-bucket latency histogram (0-7 / 8-14 / 15-30 / 31-60 / 61-90 / 90+ days), from gold_repeat_latency over the order spine. Integer day math only — single-order customers are excluded from the median. The median is shown as “—” when a brand has no repeat customers yet (never a fabricated number).',
    },
  ],
  refreshCadence:
    'The cohort + repeat-latency marts refresh on the Silver→Gold loop. Each read returns a served-at timestamp, so freshness shows the real time the BFF served it.',
  sources: [
    'gold_cohorts / mv_gold_cohorts',
    'gold_executive_metrics (repeat_rate_pct)',
    'gold_repeat_latency / mv_gold_repeat_latency (time-to-2nd-purchase)',
  ],
};

/** Sum a bigint-string column across cohorts (integer-safe; never a float). */
function sumBig(rows: AnalyticsCohortRetentionRow[], pick: (r: AnalyticsCohortRetentionRow) => string): bigint {
  return rows.reduce((acc, r) => acc + BigInt(pick(r) || '0'), 0n);
}

export function RetentionContent() {
  const cohortQ = useCohortRetention();
  const execQ = useExecutiveMetrics();
  const latencyQ = useRepeatLatency();

  const cohort = cohortQ.data;
  const exec = execQ.data;
  const latency = latencyQ.data;

  // Repeat rate is a customer-level metric; the executive endpoint returns one row per currency.
  // Use the row with the most customers as the representative headline (single-currency brands → row 0).
  const repeatRow =
    exec?.state === 'has_data' && exec.metrics.length > 0
      ? [...exec.metrics].sort((a, b) => Number(BigInt(b.distinct_customers) - BigInt(a.distinct_customers)))[0]
      : null;
  const repeatPct = repeatRow?.repeat_rate_pct ?? null;

  const cohortRows = cohort?.state === 'has_data' ? cohort.cohorts : [];
  const cohortsTracked = cohortRows.length;
  const newCustomersTracked = cohortRows.length ? sumBig(cohortRows, (r) => r.cohort_size) : 0n;

  // served_at: the BFF now returns generated_at on the cohort + executive reads, so the FreshnessBadge
  // shows a REAL relative time (honest server compute time) instead of "unknown".
  const cohortServedAt = cohort?.generated_at ?? null;
  const execServedAt = exec?.generated_at ?? null;

  return (
    <TabShell
      title="Retention"
      description="Do customers come back?"
      explainer={EXPLAINER}
      freshness={<FreshnessBadge timestamp={cohortServedAt ?? execServedAt} prefix="Served" />}
    >
      {/* ── Headline KPIs ── */}
      <div className="grid grid-cols-1 gap-4 sm:grid-cols-3">
        <MetricCard
          label="Repeat-purchase rate"
          value={repeatPct != null ? `${repeatPct}%` : undefined}
          unit={repeatPct != null ? 'of customers' : undefined}
          icon={<Repeat />}
          loading={execQ.isLoading}
          freshness={<FreshnessBadge timestamp={execServedAt} prefix="Served" />}
        />
        <MetricCard
          label="Cohorts tracked"
          value={cohortQ.isLoading ? undefined : cohortsTracked ? cohortsTracked.toLocaleString('en-IN') : undefined}
          unit={cohortsTracked ? 'acquisition months' : undefined}
          icon={<Layers />}
          loading={cohortQ.isLoading}
          freshness={<FreshnessBadge timestamp={cohortServedAt} prefix="Served" />}
        />
        <MetricCard
          label="Customers tracked"
          value={cohortQ.isLoading ? undefined : cohortsTracked ? Number(newCustomersTracked).toLocaleString('en-IN') : undefined}
          unit={cohortsTracked ? 'across all cohorts' : undefined}
          icon={<Users />}
          loading={cohortQ.isLoading}
          freshness={<FreshnessBadge timestamp={cohortServedAt} prefix="Served" />}
        />
      </div>

      {/* ── Cohort retention curve ── */}
      <SectionCard
        title={
          <span className="inline-flex items-center gap-2">
            <History className="size-4 text-muted-foreground" aria-hidden="true" />
            Acquisition-cohort curve
          </span>
        }
        description="For each month’s new customers, shaded by how strongly they came back. Switch the heatmap metric with “Shade by”; the exact figures (incl. lifetime value) are in the table below."
        meta={<FreshnessBadge timestamp={cohortServedAt} prefix="Served" />}
        flush
      >
        {cohortQ.isLoading && <TableSkeleton />}
        {!cohortQ.isLoading && cohortQ.error && (
          <div className="p-5">
            <ErrorCard error={cohortQ.error} retry={cohortQ.refetch} />
          </div>
        )}
        {!cohortQ.isLoading && !cohortQ.error && cohort?.state === 'no_data' && (
          <div className="p-5">
            <EmptyState
              icon={<Repeat />}
              title="No cohorts yet"
              description="Acquisition cohorts build once customers have placed orders. As soon as your order history syncs, each month’s new customers appear here with their repeat-purchase curve."
              action={
                <Link href="/settings/connectors">
                  <Button variant="outline" size="sm">
                    Connect your store
                    <ArrowRight className="ml-2 h-4 w-4" aria-hidden="true" />
                  </Button>
                </Link>
              }
            />
          </div>
        )}
        {!cohortQ.isLoading && !cohortQ.error && cohort?.state === 'has_data' && (
          <div className="p-5">
            <CohortRetentionPanel data={cohort} />
          </div>
        )}
      </SectionCard>

      {/* ── Time-to-2nd-purchase — median + latency histogram (gold_repeat_latency) ── */}
      <SectionCard
        title={
          <span className="inline-flex items-center gap-2">
            <Hourglass className="size-4 text-muted-foreground" aria-hidden="true" />
            Time to 2nd purchase
          </span>
        }
        description="How long customers take to come back for their second order — the median days, and the distribution across day bands."
        meta={<FreshnessBadge timestamp={latency?.generated_at} prefix="Served" />}
      >
        {latencyQ.isLoading && <LatencySkeleton />}
        {!latencyQ.isLoading && latencyQ.error && (
          <ErrorCard error={latencyQ.error} retry={latencyQ.refetch} />
        )}
        {!latencyQ.isLoading && !latencyQ.error && latency?.state === 'no_data' && (
          <EmptyState
            compact
            icon={<Hourglass />}
            title="No repeat-purchase timing yet"
            description="The time between a customer’s 1st and 2nd order appears once your order history syncs and customers start coming back. Single-order customers are excluded from the median."
          />
        )}
        {!latencyQ.isLoading && !latencyQ.error && latency?.state === 'has_data' && (
          <RepeatLatencyPanel data={latency} />
        )}
      </SectionCard>
    </TabShell>
  );
}

/** Median tile + the six-bucket time-to-2nd-purchase histogram (integer day math; never faked). */
function RepeatLatencyPanel({ data }: { data: RepeatLatencyHasData }) {
  const median = data.median_days_to_second_purchase;
  const secondOrderCustomers = Number(BigInt(data.second_order_customers));
  const totalCustomers = Number(BigInt(data.total_customers));
  // Scale the bars by the busiest bucket (integer counts; 1 floor avoids divide-by-zero).
  const maxCustomers = data.buckets.reduce((m, b) => {
    const v = Number(BigInt(b.customers));
    return v > m ? v : m;
  }, 0);
  const scale = maxCustomers || 1;

  return (
    <div className="space-y-5">
      <div className="grid grid-cols-1 gap-3 sm:grid-cols-3">
        <MetricCard
          label="Median days to 2nd order"
          value={median != null ? Number(BigInt(median)).toLocaleString('en-IN') : undefined}
          unit={median != null ? 'days' : undefined}
          icon={<Hourglass />}
        />
        <MetricCard
          label="Repeat customers"
          value={secondOrderCustomers.toLocaleString('en-IN')}
          unit="placed a 2nd order"
          icon={<Repeat />}
        />
        <MetricCard
          label="Customers tracked"
          value={totalCustomers.toLocaleString('en-IN')}
          unit="with ≥ 1 order"
          icon={<Users />}
        />
      </div>

      {median == null && (
        <p className="text-sm text-muted-foreground" role="status">
          No customers have placed a second order yet, so there is no median to report. The histogram
          fills in as repeat purchases land.
        </p>
      )}

      <div>
        <p className="mb-2 text-sm font-medium text-muted-foreground">
          Days between 1st and 2nd order
        </p>
        <ul className="space-y-3" aria-label="Time-to-2nd-purchase histogram">
          {data.buckets.map((b) => {
            const customers = Number(BigInt(b.customers));
            // Bar width is visual geometry only (not a reported figure); counts are the exact integers.
            const widthPct = Math.max(customers > 0 ? 4 : 0, Math.min(100, (customers / scale) * 100));
            return (
              <li key={b.bucket_key}>
                <div className="mb-1 flex items-center justify-between text-sm">
                  <span className="text-foreground">{b.bucket_key} days</span>
                  <span className="tabular-nums text-muted-foreground">
                    {customers.toLocaleString('en-IN')}
                    <span className="ml-1">{customers === 1 ? 'customer' : 'customers'}</span>
                  </span>
                </div>
                <div className="h-3 overflow-hidden rounded bg-muted" aria-hidden="true">
                  <div className="h-full bg-foreground/70" style={{ width: `${widthPct}%` }} />
                </div>
              </li>
            );
          })}
        </ul>
      </div>
    </div>
  );
}

function LatencySkeleton() {
  return (
    <div className="space-y-3" aria-busy="true" aria-label="Loading time-to-2nd-purchase…">
      <div className="grid grid-cols-1 gap-3 sm:grid-cols-3">
        <Skeleton className="h-24 w-full" />
        <Skeleton className="h-24 w-full" />
        <Skeleton className="h-24 w-full" />
      </div>
      <Skeleton className="h-48 w-full" />
    </div>
  );
}

// ── Cohort heatmap — client-side metric selector ──────────────────────────────
// The /v1/analytics/cohort-retention endpoint takes NO params (it returns the whole-
// history acquisition curve), so there is no server-side metric to select. Instead we
// let the operator choose which engine-derived figure SHADES the heatmap. Both options
// are EXACT integer/BigInt percentages (no floats, money never blended, never /100):
//   • repeat_order_share — (lifetime orders − cohort size) ÷ lifetime orders, the
//     share of a cohort's orders that were repeat (2nd+) purchases — the come-back signal.
//   • value_share        — a cohort's share of total lifetime realized value (bigint minor units).
// Null → an honest em-dash in the cell (never a fabricated 0).
type CohortMetricKey = 'repeat_order_share' | 'value_share';

interface CohortMetricDef {
  key: CohortMetricKey;
  /** "Shade by" selector label. */
  label: string;
  /** Heatmap column header. */
  columnLabel: string;
  /** Screen-reader caption for the grid. */
  caption: string;
}

const COHORT_METRICS: CohortMetricDef[] = [
  {
    key: 'repeat_order_share',
    label: 'Repeat-order share',
    columnLabel: 'Repeat %',
    caption:
      'Cohort retention heatmap — share of each cohort’s lifetime orders that were repeat (2nd-or-later) purchases.',
  },
  {
    key: 'value_share',
    label: 'Value share',
    columnLabel: 'Value %',
    caption: 'Cohort retention heatmap — each cohort’s share of total lifetime realized value.',
  },
];

/**
 * Exact percentage (0..100) for one cohort under the selected metric, or null when it
 * is honestly undefined (→ em-dash). All math is integer/BigInt — the inputs are bigint
 * counts / bigint minor-unit money, scaled by 10000 then read back as 2dp. No floats,
 * no blended currencies, no /100.
 */
function cohortMetricValue(
  metric: CohortMetricKey,
  row: AnalyticsCohortRetentionRow,
  totalValueMinor: bigint,
): number | null {
  if (metric === 'repeat_order_share') {
    const customers = BigInt(row.cohort_size || '0');
    const orders = BigInt(row.cohort_orders || '0');
    if (orders <= 0n) return null; // no orders → nothing to measure
    const repeat = orders > customers ? orders - customers : 0n;
    return Number((repeat * 10000n) / orders) / 100;
  }
  // value_share
  const value = BigInt(row.cohort_value_minor || '0');
  if (totalValueMinor <= 0n) return null;
  return Number((value * 10000n) / totalValueMinor) / 100;
}

/** Heatmap (rows = cohort, shaded by the chosen exact metric) + the exact-figures table. */
function CohortRetentionPanel({ data }: { data: CohortHasData }) {
  const [metricKey, setMetricKey] = useState<CohortMetricKey>('repeat_order_share');
  const metric = COHORT_METRICS.find((m) => m.key === metricKey) ?? COHORT_METRICS[0];

  // Newest cohort first — matches the exact-figures table ordering below.
  const rows = [...data.cohorts].sort((a, b) => (a.cohort_month < b.cohort_month ? 1 : -1));
  const totalValueMinor = sumBig(rows, (r) => r.cohort_value_minor);

  const heatmapRows: CohortHeatmapRow[] = rows.map((r) => ({
    label: r.cohort_month,
    size: Number(BigInt(r.cohort_size || '0')),
    cells: [{ period: 0, value: cohortMetricValue(metric.key, r, totalValueMinor) }],
  }));

  return (
    <div className="space-y-5">
      <div className="flex flex-wrap items-center gap-2" role="group" aria-label="Shade heatmap by metric">
        <span className="text-xs font-medium text-muted-foreground">Shade by</span>
        {COHORT_METRICS.map((m) => {
          const active = m.key === metricKey;
          return (
            <Button
              key={m.key}
              type="button"
              variant={active ? 'default' : 'outline'}
              size="sm"
              aria-pressed={active}
              onClick={() => setMetricKey(m.key)}
            >
              {m.label}
            </Button>
          );
        })}
      </div>

      <CohortHeatmap
        rows={heatmapRows}
        periodLabels={[metric.columnLabel]}
        cohortHeader="Cohort"
        sizeHeader="New customers"
        caption={metric.caption}
        data-testid="cohort-retention-heatmap"
      />

      <div className="space-y-2">
        <p className="text-sm font-medium text-muted-foreground">Exact figures</p>
        <CohortTable data={data} />
      </div>
    </div>
  );
}

/** Largest orders-per-customer in the set → scales the inline repeat-signal bars. */
function maxOpc(rows: CohortHasData['cohorts']): number {
  return rows.reduce((m, r) => {
    const v = r.orders_per_customer != null ? Number(r.orders_per_customer) : 0;
    return v > m ? v : m;
  }, 0);
}

function CohortTable({ data }: { data: CohortHasData }) {
  // Newest cohort first.
  const rows = [...data.cohorts].sort((a, b) => (a.cohort_month < b.cohort_month ? 1 : -1));
  const scale = maxOpc(rows) || 1;

  return (
    <Table>
      <TableHeader>
        <TableRow>
          <TableHead>Cohort</TableHead>
          <TableHead className="text-right">New customers</TableHead>
          <TableHead className="text-right">Lifetime orders</TableHead>
          <TableHead>Orders / customer</TableHead>
          <TableHead className="text-right">Lifetime value</TableHead>
        </TableRow>
      </TableHeader>
      <TableBody>
        {rows.map((r) => {
          const opc = r.orders_per_customer != null ? Number(r.orders_per_customer) : null;
          const widthPct = opc != null ? Math.max(4, Math.min(100, (opc / scale) * 100)) : 0;
          return (
            <TableRow key={r.cohort_month}>
              <TableCell className="font-medium text-foreground">{r.cohort_month}</TableCell>
              <TableCell className="text-right tabular-nums">
                {Number(BigInt(r.cohort_size)).toLocaleString('en-IN')}
              </TableCell>
              <TableCell className="text-right tabular-nums">
                {Number(BigInt(r.cohort_orders)).toLocaleString('en-IN')}
              </TableCell>
              <TableCell>
                <div className="flex items-center gap-2">
                  <span className="w-10 tabular-nums text-foreground">
                    {r.orders_per_customer ?? '—'}
                  </span>
                  <div className="h-2 flex-1 overflow-hidden rounded bg-muted" aria-hidden="true">
                    <div className="h-full bg-foreground/60" style={{ width: `${widthPct}%` }} />
                  </div>
                </div>
              </TableCell>
              <TableCell className="text-right tabular-nums">
                {formatMoneyDisplay(r.cohort_value_minor, r.currency_code as CurrencyCode)}
              </TableCell>
            </TableRow>
          );
        })}
      </TableBody>
    </Table>
  );
}

function TableSkeleton() {
  return (
    <div className="space-y-2 p-5" aria-busy="true" aria-label="Loading cohorts…">
      <Skeleton className="h-8 w-full" />
      <Skeleton className="h-8 w-full" />
      <Skeleton className="h-8 w-full" />
      <Skeleton className="h-8 w-full" />
    </div>
  );
}
