'use client';

/**
 * RetentionContent — Tab #7 "Do customers come back?".
 *
 * Answers the retention question from the existing data layer:
 *   - Repeat-purchase rate — share of customers with 2+ orders (engine-derived, exec metrics).
 *   - Acquisition-cohort curve — for each cohort-month: size, lifetime orders + value, and
 *     orders-per-customer (the repeat signal), from gold_cohorts via the metric registry.
 *
 * GAP this slice CLOSED (thin): the BFF endpoint /v1/analytics/cohort-retention + the gold_cohorts
 * mart already existed server-side, but the WEB client had no getCohortRetention fn and no hook.
 * Added analyticsApi.getCohortRetention + useCohortRetention (no new backend) — see lib/api/client.ts
 * + lib/hooks/use-analytics.ts.
 *
 * GENUINE GAP still open (flagged, NOT faked → EmptyState + openItem): "time-to-2nd-purchase"
 * (median days between a customer's 1st and 2nd order) is exposed by NO existing endpoint and would
 * need a new backend aggregate over the order spine. We do not fabricate a histogram.
 *
 * Honesty: money is bigint minor units + currency_code, formatted ONLY via formatMoneyDisplay; ratios
 * (orders_per_customer, repeat_rate_pct) come straight from the engine — never re-divided with floats
 * in the client; counts summed across cohorts use BigInt. FreshnessBadge now reads a REAL relative time
 * from the served_at (generated_at) the cohort/exec endpoints return — never a fabricated "just now".
 * EmptyState on no_data — never a fake zero.
 */

import Link from 'next/link';
import { Repeat, Users, Layers, Hourglass, ArrowRight, History } from 'lucide-react';
import type { CurrencyCode } from '@brain/money';
import { TabShell } from '@/components/ui/tab-shell';
import { SectionCard } from '@/components/ui/section-card';
import { EmptyState } from '@/components/ui/empty-state';
import { FreshnessBadge } from '@/components/ui/freshness-badge';
import { MetricCard } from '@/components/ui/metric-card';
import { Button } from '@/components/ui/button';
import { Skeleton } from '@/components/ui/skeleton';
import { ErrorCard } from '@/components/ui/error-card';
import {
  Table,
  TableHeader,
  TableBody,
  TableHead,
  TableRow,
  TableCell,
} from '@/components/ui/table';
import { formatMoneyDisplay } from '@/lib/format/money-display';
import { useCohortRetention, useExecutiveMetrics } from '@/lib/hooks/use-analytics';
import type {
  AnalyticsCohortRetentionResponse,
  AnalyticsCohortRetentionRow,
} from '@/lib/api/types';

type CohortHasData = Extract<AnalyticsCohortRetentionResponse, { state: 'has_data' }>;

const EXPLAINER = {
  title: 'Retention — Do customers come back?',
  description:
    'The overall repeat-purchase rate plus an acquisition-cohort curve: for each month’s new customers, how many lifetime orders and how much value they generate, and how many orders each makes on average.',
  metrics: [
    {
      name: 'Repeat-purchase rate',
      definition: 'Share of customers who have placed 2+ orders.',
      howComputed: 'Executive metrics repeat_rate_pct over the Gold marts (engine-derived; null when there are no customers).',
    },
    {
      name: 'Cohort size',
      definition: 'New customers first acquired in that calendar month.',
      howComputed: 'gold_cohorts, grouped by acquisition month, via /v1/analytics/cohort-retention.',
    },
    {
      name: 'Orders per customer',
      definition: 'Average lifetime orders made by that cohort — the repeat signal (>1 means customers came back).',
      howComputed: 'Exact decimal from the engine (cohort lifetime orders ÷ cohort size); null when the cohort is empty. Never re-divided in the client.',
    },
    {
      name: 'Lifetime value',
      definition: 'Total realized value generated by that cohort to date.',
      howComputed: 'gold_cohorts realized value, bigint minor units + currency_code, formatted via formatMoneyDisplay.',
    },
  ],
  sections: [
    {
      heading: 'How to read the cohort curve',
      body: 'Each row is one acquisition month. Compare orders-per-customer across rows: older cohorts have had longer to come back, so a healthy business shows orders-per-customer climbing above 1 for mature cohorts. A flat ~1.0 everywhere means customers buy once and leave.',
    },
    {
      heading: 'Time-to-2nd-purchase',
      body: 'The median days between a customer’s 1st and 2nd order is genuinely new — no endpoint exposes it yet, so it is shown as a flagged placeholder, not a fabricated histogram.',
    },
  ],
  refreshCadence:
    'The cohort mart refreshes on the Silver→Gold loop. Each read returns a served-at timestamp, so freshness shows the real time the BFF served it.',
  sources: ['gold_cohorts / mv_gold_cohorts', 'gold_executive_metrics (repeat_rate_pct)'],
};

/** Sum a bigint-string column across cohorts (integer-safe; never a float). */
function sumBig(rows: AnalyticsCohortRetentionRow[], pick: (r: AnalyticsCohortRetentionRow) => string): bigint {
  return rows.reduce((acc, r) => acc + BigInt(pick(r) || '0'), 0n);
}

export function RetentionContent() {
  const cohortQ = useCohortRetention();
  const execQ = useExecutiveMetrics();

  const cohort = cohortQ.data;
  const exec = execQ.data;

  // Repeat rate is a customer-level metric; the executive endpoint returns one row per currency.
  // Use the row with the most customers as the representative headline (single-currency brands → row 0).
  const repeatRow =
    exec?.state === 'has_data' && exec.metrics.length > 0
      ? [...exec.metrics].sort((a, b) => Number(BigInt(b.distinct_customers) - BigInt(a.distinct_customers)))[0]
      : null;
  const repeatPct = repeatRow?.repeat_rate_pct ?? null;

  const cohortRows = cohort?.state === 'has_data' ? cohort.cohorts : [];
  const cohortsTracked = cohortRows.length;
  const newCustomersTracked = cohortRows.length ? sumBig(cohortRows, (r) => r.cohort_size) : 0n;

  // served_at: the BFF now returns generated_at on the cohort + executive reads, so the FreshnessBadge
  // shows a REAL relative time (honest server compute time) instead of "unknown".
  const cohortServedAt = cohort?.generated_at ?? null;
  const execServedAt = exec?.generated_at ?? null;

  return (
    <TabShell
      title="Retention"
      description="Do customers come back?"
      explainer={EXPLAINER}
      freshness={<FreshnessBadge timestamp={cohortServedAt ?? execServedAt} prefix="Served" />}
    >
      {/* ── Headline KPIs ── */}
      <div className="grid grid-cols-1 gap-4 sm:grid-cols-3">
        <MetricCard
          label="Repeat-purchase rate"
          value={repeatPct != null ? `${repeatPct}%` : undefined}
          unit={repeatPct != null ? 'of customers' : undefined}
          icon={<Repeat />}
          loading={execQ.isLoading}
          freshness={<FreshnessBadge timestamp={execServedAt} prefix="Served" />}
        />
        <MetricCard
          label="Cohorts tracked"
          value={cohortQ.isLoading ? undefined : cohortsTracked ? cohortsTracked.toLocaleString('en-IN') : undefined}
          unit={cohortsTracked ? 'acquisition months' : undefined}
          icon={<Layers />}
          loading={cohortQ.isLoading}
          freshness={<FreshnessBadge timestamp={cohortServedAt} prefix="Served" />}
        />
        <MetricCard
          label="Customers tracked"
          value={cohortQ.isLoading ? undefined : cohortsTracked ? Number(newCustomersTracked).toLocaleString('en-IN') : undefined}
          unit={cohortsTracked ? 'across all cohorts' : undefined}
          icon={<Users />}
          loading={cohortQ.isLoading}
          freshness={<FreshnessBadge timestamp={cohortServedAt} prefix="Served" />}
        />
      </div>

      {/* ── Cohort retention curve ── */}
      <SectionCard
        title={
          <span className="inline-flex items-center gap-2">
            <History className="size-4 text-muted-foreground" aria-hidden="true" />
            Acquisition-cohort curve
          </span>
        }
        description="For each month’s new customers: lifetime orders, lifetime value, and orders per customer (the come-back signal)."
        meta={<FreshnessBadge timestamp={undefined} />}
        flush
      >
        {cohortQ.isLoading && <TableSkeleton />}
        {!cohortQ.isLoading && cohortQ.error && (
          <div className="p-5">
            <ErrorCard error={cohortQ.error} retry={cohortQ.refetch} />
          </div>
        )}
        {!cohortQ.isLoading && !cohortQ.error && cohort?.state === 'no_data' && (
          <div className="p-5">
            <EmptyState
              icon={<Repeat />}
              title="No cohorts yet"
              description="Acquisition cohorts build once customers have placed orders. As soon as your order history syncs, each month’s new customers appear here with their repeat-purchase curve."
              action={
                <Link href="/settings/connectors">
                  <Button variant="outline" size="sm">
                    Connect your store
                    <ArrowRight className="ml-2 h-4 w-4" aria-hidden="true" />
                  </Button>
                </Link>
              }
            />
          </div>
        )}
        {!cohortQ.isLoading && !cohortQ.error && cohort?.state === 'has_data' && (
          <CohortTable data={cohort} />
        )}
      </SectionCard>

      {/* ── Time-to-2nd-purchase (flagged gap — never faked) ── */}
      <SectionCard
        title={
          <span className="inline-flex items-center gap-2">
            <Hourglass className="size-4 text-muted-foreground" aria-hidden="true" />
            Time to 2nd purchase
          </span>
        }
        description="How long customers take to come back for their second order."
      >
        <EmptyState
          compact
          icon={<Hourglass />}
          title="Not available yet"
          description="The median days between a customer’s 1st and 2nd order needs a new backend aggregate over the order spine — no endpoint exposes it today. We’re flagging it rather than showing a fabricated histogram."
        />
      </SectionCard>
    </TabShell>
  );
}

/** Largest orders-per-customer in the set → scales the inline repeat-signal bars. */
function maxOpc(rows: CohortHasData['cohorts']): number {
  return rows.reduce((m, r) => {
    const v = r.orders_per_customer != null ? Number(r.orders_per_customer) : 0;
    return v > m ? v : m;
  }, 0);
}

function CohortTable({ data }: { data: CohortHasData }) {
  // Newest cohort first.
  const rows = [...data.cohorts].sort((a, b) => (a.cohort_month < b.cohort_month ? 1 : -1));
  const scale = maxOpc(rows) || 1;

  return (
    <Table>
      <TableHeader>
        <TableRow>
          <TableHead>Cohort</TableHead>
          <TableHead className="text-right">New customers</TableHead>
          <TableHead className="text-right">Lifetime orders</TableHead>
          <TableHead>Orders / customer</TableHead>
          <TableHead className="text-right">Lifetime value</TableHead>
        </TableRow>
      </TableHeader>
      <TableBody>
        {rows.map((r) => {
          const opc = r.orders_per_customer != null ? Number(r.orders_per_customer) : null;
          const widthPct = opc != null ? Math.max(4, Math.min(100, (opc / scale) * 100)) : 0;
          return (
            <TableRow key={r.cohort_month}>
              <TableCell className="font-medium text-foreground">{r.cohort_month}</TableCell>
              <TableCell className="text-right tabular-nums">
                {Number(BigInt(r.cohort_size)).toLocaleString('en-IN')}
              </TableCell>
              <TableCell className="text-right tabular-nums">
                {Number(BigInt(r.cohort_orders)).toLocaleString('en-IN')}
              </TableCell>
              <TableCell>
                <div className="flex items-center gap-2">
                  <span className="w-10 tabular-nums text-foreground">
                    {r.orders_per_customer ?? '—'}
                  </span>
                  <div className="h-2 flex-1 overflow-hidden rounded bg-muted" aria-hidden="true">
                    <div className="h-full bg-foreground/60" style={{ width: `${widthPct}%` }} />
                  </div>
                </div>
              </TableCell>
              <TableCell className="text-right tabular-nums">
                {formatMoneyDisplay(r.cohort_value_minor, r.currency_code as CurrencyCode)}
              </TableCell>
            </TableRow>
          );
        })}
      </TableBody>
    </Table>
  );
}

function TableSkeleton() {
  return (
    <div className="space-y-2 p-5" aria-busy="true" aria-label="Loading cohorts…">
      <Skeleton className="h-8 w-full" />
      <Skeleton className="h-8 w-full" />
      <Skeleton className="h-8 w-full" />
      <Skeleton className="h-8 w-full" />
    </div>
  );
}
